[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
serde = "1.0.219"
tokio = { version = "1.44.2", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-rustls"] }
serde_json = "1.0.140"
dotenvy = "0.15.7"
tracing = "0.1.41"
